# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-29 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FOGO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lat',
            field=models.CharField(default='0', max_length=60),
        ),
        migrations.AlterField(
            model_name='user',
            name='lon',
            field=models.CharField(default='0', max_length=60),
        ),
    ]
